version: 2
jobs:
  build:
    working_directory: ~/prp-site
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: angular-build
          command: ng --build --prod --aot --no-progress
#      - run:
#          name: angular-test
#          command: yarn test -- --single-run --no-progress
#      - run:
#          name: angular-lint
#          command: yarn lint
