version: 2
jobs:
  build:
    working_directory: ~/prp-site
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --no-progress
      - persist_to_workspace:
          root: ~/prp-site
          paths:
            - dist
  deploy:
      docker:
        - image: cibuilds/aws:2.1.18
      working_directory: ~/prp-site
      steps:
        - attach_workspace:
            at: ./generated-site
        - run:
            name: Deploy to S3
            command: aws s3 sync generated-site/dist s3://partyrollpodcast.com/ --delete
        - run:
            name: Invalidate cache
            command: aws cloudfront create-invalidation --distribution-id $AWS_DIST_ID --paths "/*"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
