version: 2
jobs:
  build:
    working_directory: ~/prp-site
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - persist_to_workspace:
          root: ~/prp-site
          paths:
            - dist
  deploy:
      docker:
        - image: cibuilds/aws:1.15.44
      working_directory: ~/prp-site
      steps:
        - attach_workspace:
            at: ./generated-site
        - run:
            name: Deploy to S3
            command: aws s3 sync generated-site/dist s3://partyrollpodcast.com/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
