version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
#      - run:
#          name: angular-test
#          command: yarn test -- --single-run --no-progress
#      - run:
#          name: angular-lint
#          command: yarn lint
